#!/usr/bin/env sh
[ -d $HOME/.local/bootstrap ] || mkdir -p $HOME/.local/bootstrap
curl -fsSLo $HOME/.local/bootstrap/syvl https://raw.githubusercontent.com/shadowrylander/syvl/main/syvl
chmod +x $HOME/.local/bootstrap/syvl
$HOME/.local/bootstrap/syvl --init
dependencies="rsync sd"
for prog in $dependencies; do hash $prog 2>/dev/null || $pacapt -yyu 2>/dev/null && break || :; done
for prog in $dependencies; do hash $prog 2>/dev/null || $pacapt -S $prog 2>/dev/null || nix-env -iA nixos.$prog; done
chmod +x bootstrap
echo
echo 'source $HOME/.local/syvl/python/bin/activate'
