.RECIPEPREFIX := |

init:
|-git clone --recurse-submodule https://github.com/scop/bash-completion ~//resources/bashCompletions
|-git clone --recurse-submodule https://github.com/xero/figlet-fonts ~//resources/xeroFigletFonts
|-git clone --recurse-submodule https://github.com/grml/grml-etc-core ~//resources/grml
|-git clone --recurse-submodule https://github.com/SpaceVim/SpaceVim ~//home/.vim
|-git clone --recurse-submodule https://github.com/dexpota/kitty-themes ~//resources/kittyThemes
|-git clone --recurse-submodule https://github.com/aleclearmind/nested-tmux ~//resources/aleclearmind
|-git clone --recurse-submodule https://github.com/gpakosz/.tmux ~//resources/oh-my-tmux
|-git clone --recurse-submodule https://github.com/powerline/powerline ~//resources/powerline
|-git clone --recurse-submodule https://github.com/tmux-plugins/tpm ~//resources/tpm
|-ln -sf home/.vim ~//home/.config/nvim
