.RECIPEPREFIX := |

init:
|-git clone --recurse-submodule https://github.com/scop/bash-completion ~/shadowrylander/resources/bashCompletions
|-git clone --recurse-submodule https://github.com/xero/figlet-fonts ~/shadowrylander/resources/xeroFigletFonts
|-git clone --recurse-submodule https://github.com/grml/grml-etc-core ~/shadowrylander/resources/grml
|-git clone --recurse-submodule https://github.com/SpaceVim/SpaceVim ~/shadowrylander/home/.vim
|-git clone --recurse-submodule https://github.com/dexpota/kitty-themes ~/shadowrylander/resources/kittyThemes
|-git clone --recurse-submodule https://github.com/aleclearmind/nested-tmux ~/shadowrylander/resources/aleclearmind
|-git clone --recurse-submodule https://github.com/gpakosz/.tmux ~/shadowrylander/resources/oh-my-tmux
|-git clone --recurse-submodule https://github.com/powerline/powerline ~/shadowrylander/resources/powerline
|-git clone --recurse-submodule https://github.com/tmux-plugins/tpm ~/shadowrylander/resources/tpm
|-ln -sf home/.vim ~/shadowrylander/home/.config/nvim
