#!/usr/bin/env sh
getSecret() {
    # Adapted From: https://stackoverflow.com/a/3980713/10827766
    set +o history
    stty -echo
    printf "$1: "
    shift
    read secret
    stty echo
    printf "\n"
    echo $secret | $@
    set -o history
}

# Adapted From: https://askubuntu.com/a/15856/1058868
inRoot() { [[ $EUID -eq 0 ]] && $1 || : }
notInRoot() { [[ $EUID -ne 0 ]] && $1 || : }

inAndroid() { [[ $(uname -a) == *Android* ]] && $1 || : }
notInAndroid() { [[ $(uname -a) != *Android* ]] && $1 || : }
inUbuntu() { [[ $(uname -a) == *Ubuntu* ]] && $1 || : }
notInUbuntu() { [[ $(uname -a) != *Ubuntu* ]] && $1 || : }
inNixOS() { [[ $(uname -a) == *NixOS* ]] && $1 || : }
notInNixOS() { [[ $(uname -a) != *NixOS* ]] && $1 || : }
