#!/usr/bin/env zsh
# Adapted From: https://askubuntu.com/a/15856/1058868
if [[ $EUID -ne 0 ]]; then
    root="~"
    ylv="$root/ylv/ylv"
else
    root="/root"
    ylv="/ylv/ylv su"
fi

$ylv -Y $root/.config/yadm-sec --yadm-dir $root/.local/share/yadm-sec
