#!/usr/bin/env zsh
if [[ -n "$1" ]]; then
    if [[ -n "$2" ]]; then
        ($1 cnm && $1 $2) || $1 $2
    else
        ($1 cnm && $1 push) || $1 push
    fi
else
    (git cnm && git push) || git push || (git cnm && git noggin) || git noggin || (yadm cnm && yadm push) || yadm push
fi
