.RECIPEPREFIX := |

init:
|-git clone --recurse-submodule https://github.com/shadowrylander/emacs-bankruptcy ~/shadowrylander/home/.doom.d/emacs-bankruptcy
|-git clone --recurse-submodule https://github.com/chenyanming/spacemacs_module_for_doom ~/shadowrylander/home/.doom.d/modules/private/spacemacs
|-git clone --recurse-submodule https://gitlab.com/
.DEFAULT_GOAL := init
