init:
    -git clone --recurse-submodule https://github.com/shadowrylander/emacs-bankruptcy
    -git clone --recurse-submodule https://github.com/chenyanming/spacemacs_module_for_doom modules/private/spacemacs
    -git clone --recurse-submodule https://gitlab.com/picotech/use-package-hydra
    -git clone --recurse-submodule https://gitlab.com/shadowrylander/use-package-hercules
.DEFAULT_GOAL := init
