.RECIPEPREFIX := |

init:
|-git clone --recurse-submodule https://github.com/shadowrylander/emacs-bankruptcy home/.doom.d/emacs-bankruptcy
|-git clone --recurse-submodule https://github.com/chenyanming/spacemacs_module_for_doom home/.doom.d/modules/private/spacemacs
|-git clone --recurse-submodule https://gitlab.com/picotech/use-package-hydra home/.doom.d/use-package-hydra
|-git clone --recurse-submodule https://gitlab.com/shadowrylander/use-package-hercules home/.doom.d/use-package-hercules
.DEFAULT_GOAL := init
